include:
  - docker-compose.base.yml


services:

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8089:8080

  angular-dev:
    container_name: angular_dev_container
    build:
      context: .
      dockerfile: .docker/angular/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ${HOME}/storage  # Home-Verzeichnis des Benutzers
        target: /app/storage  
    stdin_open: true
    tty: true
    environment:
      DASHBOARD_LOGIN_PASSWORD: ${DASHBOARD_LOGIN_PASSWORD}