include:
  - docker-compose.base.yml

services:
  angular:
    container_name: angular_container
    build:
      context: .
      dockerfile: .docker/angular/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ${HOME}/storage # Home-Verzeichnis des Benutzers
        target: /app/storage
    image: kopfdesdaemons/grundbuch-musterantrag-angular:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DASHBOARD_ROOT_USER: ${DASHBOARD_ROOT_USER}
      DASHBOARD_ROOT_PASSWORD: ${DASHBOARD_ROOT_PASSWORD}
      NODE_ENV: production
