services:

  angular:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ${HOME}/storage  # Home-Verzeichnis des Benutzers
        target: /app/storage  
    image: kopfdesdaemons/grundbuch-musterantrag.de:latest
    environment:
      DASHBOARD_LOGIN_PASSWORD: ${DASHBOARD_LOGIN_PASSWORD}
