include:
  - docker-compose.base.yml

services:
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8089:8080

  angular-dev:
    container_name: angular_dev_container
    build:
      context: .
      dockerfile: .docker/angular/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./server/templates
        target: /templates
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DASHBOARD_ROOT_USER: ${DASHBOARD_ROOT_USER}
      DASHBOARD_ROOT_PASSWORD: ${DASHBOARD_ROOT_PASSWORD}
      NODE_ENV: development
