FROM node:24.12.0-alpine AS dev

WORKDIR /app

RUN apk add --no-cache libreoffice openjdk8-jre

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm ci

EXPOSE 4200

USER node

CMD ["npm", "start", "--", "--host=0.0.0.0"]