name: Deploy to Server (Docker)

on:
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build Angular
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/angular/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/grundbuch-musterantrag-angular:latest

  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      - name: Create directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          source: ./docker-compose.yml
          target: /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/docker-compose.yml
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy using SSH Private Key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/
            docker-compose pull
            DASHBOARD_LOGIN_PASSWORD=${{ secrets.DASHBOARD_LOGIN_PASSWORD }} \
            docker-compose up -d
