name: Deploy to Server (Docker)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/angular/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/grundbuch-musterantrag-angular:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deployment to Server
    needs: [build-and-push]
    steps:
      - name: Create directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Ordner des Projekts
            install -d -o ${{ secrets.SSH_USER }} -g ${{ secrets.SSH_USER }} /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          source: ./docker-compose.yml
          target: /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.base.yml to server
        uses: appleboy/scp-action@master
        with:
          source: ./docker-compose.base.yml
          target: /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy using SSH Private Key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/
            docker compose down

            # Setzen der Variablen
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            MYSQL_USER=${{ secrets.MYSQL_USER }} \
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            DASHBOARD_ROOT_USER=${{ secrets.DASHBOARD_ROOT_USER }} \
            DASHBOARD_ROOT_PASSWORD=${{ secrets.DASHBOARD_ROOT_PASSWORD }} \
            docker compose up -d --pull always

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Remove unused Docker images, volumes and networks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/app/grundbuch-musterantrag.de/
            docker image prune -af
            docker volume prune -f
            docker network prune -f
