name: Deploy to Server

on:
  workflow_dispatch: # Erlaubt manuelles Auslösen des Workflows

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DASHBOARD_LOGIN_PASSWORD: ${{ secrets.DASHBOARD_LOGIN_PASSWORD }}

    steps:
      # Checkout, um auf den Repository-Code zuzugreifen
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Backup der aktuellen Version
      - name: Backup current version
        run: |
          ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "cp -r /var/www/grundbuch-musterantrag.de ~/grundbuch-musterantrag.de_backup_$(date +'%Y%m%d%H%M%S')"

      # Baue die Angular-Anwendung
      - name: Build Angular app
        run: |
          npm install
          npm run build --prod

      # Deployment der Anwendung auf den Server
      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ rico@217.160.208.184:/var/www/grundbuch-musterantrag.de

      # Neustart der Node.js-Anwendung mit PM2
      - name: Restart PM2 application
        run: |
          ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "export DASHBOARD_LOGIN_PASSWORD=${DASHBOARD_LOGIN_PASSWORD} && pm2 restart server --update-env"

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    steps:
      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Rollback zur letzten Sicherung
      - name: Rollback to previous version
        run: |
          BACKUP_DIR=$(ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "ls -td ~/grundbuch-musterantrag.de_backup_* | head -n 1")
          ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "rm -rf /var/www/grundbuch-musterantrag.de"
          ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "mv $BACKUP_DIR /var/www/grundbuch-musterantrag.de"

      # Neustart der Node.js-Anwendung mit PM2 nach Rollback
      - name: Restart PM2 application after rollback
        run: |
          ssh -o StrictHostKeyChecking=no rico@217.160.208.184 "pm2 restart server"
