name: Deploy to Server

on:
  workflow_dispatch: # Erlaubt manuelles Auslösen des Workflows

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout, um auf den Repository-Code zuzugreifen
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Baue die Angular-Anwendung
      - name: Build Angular app
        run: |
          npm install
          npm run build --prod

      # Deployment der Anwendung auf den Server
      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ rico@217.160.208.184:/var/www/grundbuch-musterantrag.de
