name: Deploy to Server

on:
  workflow_dispatch: # Erlaubt manuelles Auslösen des Workflows

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DASHBOARD_LOGIN_PASSWORD: ${{ secrets.DASHBOARD_LOGIN_PASSWORD }}
      SERVER_USER: rico
      SERVER_HOST: 217.160.208.184
      TARGET_DIR: /var/www/html/grundbuch-musterantrag.de
      BACKUP_DIR: ~/grundbuch-musterantrag.de_backup_$(date +'%Y%m%d%H%M%S')

    steps:
      # Checkout, um auf den Repository-Code zuzugreifen
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Backup der aktuellen Version
      - name: Backup current version
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "cp -r $TARGET_DIR $BACKUP_DIR"

      # Baue die Angular-Anwendung
      - name: Build Angular app
        run: |
          npm install
          npm run build --prod

      # Löschen des Zielordners auf dem Server
      - name: Clear target directory on server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf $TARGET_DIR/*"

      # Deployment der Anwendung auf den Server
      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/grundbuch-musterantrag.de/ $SERVER_USER@$SERVER_HOST:$TARGET_DIR

      # Neustart der Node.js-Anwendung mit PM2
      - name: Restart PM2 application
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "export DASHBOARD_LOGIN_PASSWORD=${DASHBOARD_LOGIN_PASSWORD} && pm2 restart server --update-env"

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    env:
      SERVER_USER: rico
      SERVER_HOST: 217.160.208.184
      TARGET_DIR: /var/www/html/grundbuch-musterantrag.de

    steps:
      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Rollback zur letzten Sicherung
      - name: Rollback to previous version
        run: |
          BACKUP_DIR=$(ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "ls -td ~/grundbuch-musterantrag.de_backup_* | head -n 1")
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf $TARGET_DIR"
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mv $BACKUP_DIR $TARGET_DIR"

      # Neustart der Node.js-Anwendung mit PM2 nach Rollback
      - name: Restart PM2 application after rollback
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "pm2 restart server"
