name: Rollback to Previous Version

on:
  workflow_dispatch: # Erlaubt manuelles Auslösen des Workflows

jobs:
  rollback:
    runs-on: ubuntu-latest

    env:
      SERVER_USER: rico
      SERVER_HOST: 217.160.208.184
      TARGET_DIR: /var/www/html/grundbuch-musterantrag.de

    steps:
      # Konfiguration der SSH-Verbindung
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Rollback zur letzten Sicherung
      - name: Rollback to previous version
        run: |
          BACKUP_DIR=$(ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "ls -td ~/grundbuch-musterantrag.de_backup_* | head -n 1")
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf $TARGET_DIR"
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mv $BACKUP_DIR $TARGET_DIR"

      # Neustart der Node.js-Anwendung mit PM2 nach Rollback
      - name: Restart PM2 application after rollback
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "pm2 restart server"
